List<AlignmentModel>  alignmentResponseList(var json) {
  return List<AlignmentModel>.from(json.map((x) => AlignmentModel.fromJson(x)));
}

class AlignmentModel {
  String? id;
  String? alignmentName;
  String? chainageFrom;
  String? chainageTo;

  AlignmentModel(
      {this.id, this.alignmentName, this.chainageFrom, this.chainageTo});

  AlignmentModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    alignmentName = json['alignment_name'];
    chainageFrom = json['chainage_from'];
    chainageTo = json['chainage_to'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['alignment_name'] = this.alignmentName;
    data['chainage_from'] = this.chainageFrom;
    data['chainage_to'] = this.chainageTo;
    return data;
  }
}
class Autogenerated {
  String? id;
  String? alignmentName;
  String? chainageFrom;
  String? chainageTo;

  Autogenerated(
      {this.id, this.alignmentName, this.chainageFrom, this.chainageTo});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    alignmentName = json['alignment_name'];
    chainageFrom = json['chainage_from'];
    chainageTo = json['chainage_to'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['alignment_name'] = this.alignmentName;
    data['chainage_from'] = this.chainageFrom;
    data['chainage_to'] = this.chainageTo;
    return data;
  }
}